# Step 1: Build the Spring Boot app using Gradle
FROM gradle:7.6.0-jdk17 AS build
WORKDIR /app

# Gradle 캐시 활용을 위해 build.gradle과 settings.gradle 먼저 복사
COPY build.gradle settings.gradle ./

# 종속성 다운로드
RUN gradle build --no-daemon -x test || return 0

# 소스 코드 복사
COPY src ./src

# 환경 변수 ARG 설정
ARG SPRING_RABBITMQ_USERNAME
ARG SPRING_RABBITMQ_PASSWORD
ARG SPRING_RABBITMQ_HOST
ARG SPRING_RABBITMQ_PORT

ARG DATABASE_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ARG OPENAI_API_KEY
ARG OPENAI_API_URL
ARG OPENAI_MODEL

ARG KAKAO_CLIENT_ID
ARG KAKAO_AUTHORIZATION_URI
ARG KAKAO_USER_INFO_URI
ARG KAKAO_REDIRECT_URI
ARG KAKAO_API_KEY

# 환경 변수를 .env 파일에 기록
RUN echo "SPRING_RABBITMQ_USERNAME=$SPRING_RABBITMQ_USERNAME" >> src/main/resources/application.properties
RUN echo "SPRING_RABBITMQ_PASSWORD=$SPRING_RABBITMQ_PASSWORD" >> src/main/resources/application.properties
RUN echo "SPRING_RABBITMQ_HOST=$SPRING_RABBITMQ_HOST" >> src/main/resources/application.properties
RUN echo "SPRING_RABBITMQ_PORT=$SPRING_RABBITMQ_PORT" >> src/main/resources/application.properties

RUN echo "DATABASE_URL=$DATABASE_URL" >> src/main/resources/application.properties
RUN echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> src/main/resources/application.properties
RUN echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> src/main/resources/application.properties

RUN echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> src/main/resources/application.properties
RUN echo "OPENAI_API_URL=$OPENAI_API_URL" >> src/main/resources/application.properties
RUN echo "OPENAI_MODEL=$OPENAI_MODEL" >> src/main/resources/application.properties

RUN echo "KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID" >> src/main/resources/application.properties
RUN echo "KAKAO_AUTHORIZATION_URI=$KAKAO_AUTHORIZATION_URI" >> src/main/resources/application.properties
RUN echo "KAKAO_USER_INFO_URI=$KAKAO_USER_INFO_URI" >> src/main/resources/application.properties
RUN echo "KAKAO_REDIRECT_URI=$KAKAO_REDIRECT_URI" >> src/main/resources/application.properties
RUN echo "KAKAO_API_KEY=$KAKAO_API_KEY" >> src/main/resources/application.properties

# Gradle 빌드 실행 (테스트 제외)
RUN gradle build --no-daemon -x test

# Step 2: Run the Spring Boot app
FROM openjdk:17-jdk-slim
COPY --from=build /app/build/libs/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]